- harvestingkit/scripts/fix_marc_record.py
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>
> fix_marc_record.py to fix FFT

- harvestingkit/scripts/fix_marc_record.py
* Integrate support for stripping BOM and for simply concatenate
multiple files taken from the command line.
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>
> fix_marc_record.py: final version

- harvestingkit/scripts/fix_marc_record.py
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>
> fix_marc_record.py: amends initials and dots

- harvestingkit/pos_package.py
- harvestingkit/tests/data/sample_pos_record.xml
- harvestingkit/tests/pos_package_tests.py
> New metadata format for PoS

- harvestingkit/pos_package.py
- harvestingkit/tests/__init__.py
- harvestingkit/tests/pos_package_tests.py
Title fix and cosmetics.
@fschwenn
> Pos title fix

- harvestingkit/bibrecord.py
- harvestingkit/html_utils.py
- harvestingkit/tests/html_utils_tests.py
- harvestingkit/tests/utils_tests.py
- harvestingkit/utils.py
* Provide an alternative legacy XML escape function to BibRecord
and improve existing one to work for most cases.
> utils: refactor XML escaping

- harvestingkit/tests/utils_tests.py
- harvestingkit/utils.py
> utils: yet another round of XML escaping

- harvestingkit/contrast_out.py
Signed-off-by: Wojciech Ziolek <wojciech.ziolek@cern.ch
> contrast_out: fix missing MD5Error import

- harvestingkit/config.py
- harvestingkit/tests/utils_tests.py
- harvestingkit/utils.py
* config.py: added OA_LICENSES
* utils.py: added license_is_oa
Signed-off-by: Kirsten Sachs <kirsten.sachs@desy.de>
> harvestingkit: determine OA from license

- harvestingkit/app_utils.py
Signed-off-by: Wojciech Ziółek <wojciech.ziolek@cern.ch>
> Changes app_utils to use harvestingkit.bibrecord

- harvestingkit/nlm_utils.py
Signed-off-by: Wojciech Ziółek <wojciech.ziolek@cern.ch>
> Fixes NLM harvesting when reference type is missing.

- harvestingkit/world_scientific_package.py
> world_scientific: fix date parsing

- harvestingkit/inspire_cds_package/base.py
- harvestingkit/inspire_cds_package/from_inspire.py
- harvestingkit/tests/data/sample_inspire_oai.xml
- harvestingkit/tests/inspire_cds_package_tests.py
> inspire2cds: add CDS recid if present

- harvestingkit/inspire_cds_package/from_inspire.py
> inspire2cds: fix journal names on CDS

- harvestingkit/jats_package.py
* Fixes an exception that could happen when adding authors
in a JATS conversion.
@fschwenn
> jats_package: fix for authors

- harvestingkit/pos_package.py
avoids empty affiliations in bibupload 
https://github.com/inspirehep/harvesting-kit/issues/157
Signed-off-by: Thorsten Schwander <thorsten.schwander@gmail.com>
> pos_package: avoid empty affiliations

- harvestingkit/elsevier_package.py
- harvestingkit/tests/utils_tests.py
- harvestingkit/utils.py
* set default timeout=60 in requests.get()
* adds a User-Agent header to requests.get()
* adds User-Agent version string formatter
Signed-off-by: Thorsten Schwander <thorsten.schwander@gmail.com>
> adds timeout and User-Agent to requests

- harvestingkit/inspire_cds_package/mappings.py
* Amends mapping of JHEP, JINST, JCAP so that CDS uses the same format of INSPIRE.
> JHEP, JINST, JCAP

- harvestingkit/elsevier_package.py
I made the requested change to my previous request (#155)
> Elsevierdate

- setup.py
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>
> setup: add missing data files

- harvestingkit/tests/utils_tests.py
- harvestingkit/utils.py
Signed-off-by: Thorsten Schwander <thorsten.schwander@gmail.com>
> improve journal name normalization

- harvestingkit/inspire_cds_package/from_inspire.py
- harvestingkit/tests/inspire_cds_package_tests.py
* remove the change of the tag 700 -> 701 on request of the CERN library
(SNOW: RQF1302222)
> inspire_cds_package: fix tag thesis supervisor

- .travis.yml
- harvestingkit/inspire_cds_package/from_inspire.py
- harvestingkit/tests/data/sample_inspire_oai.xml
- harvestingkit/tests/inspire_cds_package_tests.py
- setup.py
https://cern.service-now.com/service-portal/view-request.do?n=RQF1529465
> Inspire to cds fixes

- .travis.yml
- harvestingkit/inspire_cds_package/from_inspire.py
- harvestingkit/tests/data/sample_inspire_oai.xml
- harvestingkit/tests/inspire_cds_package_tests.py
* copy experiment name in tag 693__b when available
> inspire_cds_package: fix experiment 693__b

- harvestingkit/elsevier_package.py
- setup.py
Signed-off-by: Thorsten Schwander <thorsten.schwander@gmail.com>
> elsevier_package: handle abs with paragraphs

- harvestingkit/inspire_cds_package/from_inspire.py
- harvestingkit/tests/inspire_cds_package_tests.py
- setup.py
Updates articles and preprints rules when harvesting from Inspire
> inspire_cds_package: Updates articles rules
